### ISSUE TITLE
skydive-flow-matrix --format render OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by patsevanton** [skydive-project/skydive-flow-matrix#9]
Hello!
i try run render on CentOS 7:

```
git clone https://github.com/skydive-project/skydive-flow-matrix.git
cd skydive-flow-matrix
sudo pip install virtualenv
virtualenv .venv
source .venv/bin/activate
pip install -r requirements.txt
pip install .
sudo yum install -y graphviz
```

```
skydive-flow-matrix --analyzer 172.26.9.72:8082 --username admin --password password --format render --engine circo
Traceback (most recent call last):
  File "/home/centos/skydive-flow-matrix/.venv/bin/skydive-flow-matrix", line 8, in <module>
    sys.exit(main())
  File "/home/centos/skydive-flow-matrix/.venv/lib/python2.7/site-packages/matrix/matrix.py", line 447, in main
    dot_output(matrix, args.engine, args.format == "render")
  File "/home/centos/skydive-flow-matrix/.venv/lib/python2.7/site-packages/matrix/matrix.py", line 326, in dot_output
    g.view()
  File "/home/centos/skydive-flow-matrix/.venv/lib64/python2.7/site-packages/graphviz/files.py", line 242, in view
    quiet=quiet, quiet_view=quiet_view)
  File "/home/centos/skydive-flow-matrix/.venv/lib64/python2.7/site-packages/graphviz/files.py", line 216, in render
    self._view(rendered, self._format, quiet_view)
  File "/home/centos/skydive-flow-matrix/.venv/lib64/python2.7/site-packages/graphviz/files.py", line 258, in _view
    view_method(filepath, quiet)
  File "/home/centos/skydive-flow-matrix/.venv/lib64/python2.7/site-packages/graphviz/backend.py", line 287, in view_unixoid
    popen_func(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

What is file need?

**Comment by safchain** [comment]
Per the graphviz code it tries to open  `xdg-open...` seems to be an graphviz related issue. I would try to change the engine `--engine` and the format `--format`

**Comment by patsevanton** [comment]
I run skydive-flow-matrix on server without GUI.
May be run on PC with GUI?

**Comment by safchain** [comment]
yes maybe from a pc with GUI or using another output format like csv then a spreadsheet
